<script>
function setIframeHeight()
{
    var iframe = document.getElementById("loadpageIframeId");   
    var iframeWin = iframe.contentWindow || iframe.contentDocument.parentWindow;
    if (iframeWin.document.body) {
        iframe.height = iframeWin.document.documentElement.scrollHeight || iframeWin.document.body.scrollHeight;
    }
};
var docUrl = '<?php echo $this->url('/doc/load/', array('sPath' => $this->docPath, 'sMode'=>'view'), 'doc')?>';
function changeView()
{
    $('#loadpageIframeId').get(0).src = docUrl;
}
__wait(function(){
    $('#editId').click(function(){
        $('#loadpageIframeId').get(0).src = this.href;
    });
});
</script>
<div style="border-bottom: 1px solid #000;">
    <a id="editId" href="<?php echo $this->url('/doc/load/', array('sPath' => $this->docPath, 'sMode'=>'edit'), 'doc')?>" onclick="return false;">编辑</a>
</div>
<div>
<iframe id="loadpageIframeId" src="<?php echo $this->url('/doc/load/', array('sPath' => $this->docPath, 'sMode'=>'view'), 'doc')?>" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" style="width:100%;min-height:500px;"></iframe>
</div>