<?php
$this->script()->appendScript('http://asset.bxshare.cn/technology_doc/js/??modules/editormd/lib/marked.min.js,modules/editormd/lib/prettify.min.js,modules/editormd/lib/raphael.min.js,modules/editormd/lib/underscore.min.js,modules/editormd/lib/sequence-diagram.min.js,modules/editormd/lib/flowchart.min.js,modules/editormd/lib/jquery.flowchart.min.js,modules/editormd/editormd.min.js');
?>

<div id="test-editormd-view" class="markdown-body editormd-html-preview" style="padding:0px;">
    <textarea style="display:none;"><?php echo $this->mdContent?></textarea>
</div>
<script type="text/javascript">
    __wait(function(){
        editormd.markdownToHTML("test-editormd-view", {
            htmlDecode : "style,script,iframe|on*",
            emoji : false,
            taskList : true,
            tocm : true,
            tex : true,
            flowChart : true,
            sequenceDiagram : true
        });
    });
</script>