<!doctype html> 
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $this->headTitle('开放空间 - 文档馆')?></title>
        <?php echo $this->headMeta('开放空间', 'keywords')->headMeta('开放空间', 'description')?>
        <?php $this->headLink()->prependStylesheet('/asset/css/page/md_shell.css')?>
        <?php echo $this->headLink()?>
        <?php echo $this->initPageNecessary()?>
    </head>
    <body>
        <div class="container-fluid fluid-height wrapper">
			<div class="navbar navbar-default navbar-fixed-top">
				<div class="navbar-inner">
					<a class="brand pull-left" href="<?php echo $this->homepageUrl;?>">开放空间 - 文档馆</a>
				</div>
			</div>

			<div class="row-fluid columns content">
				<div class="left-column article-tree span3">
					<div id="sub-nav-collapse" class="collapse in">
						<!-- Navigation -->
						<?php echo $this->navTrees; ?>
					</div>
				</div>
				<div class="right-column content-area span9">
					<div class="content-page">
						<article>
                            <?php echo $scriptContent ?>
						</article>
					</div>
				</div>
			</div>
		</div>
       
        <?php
        echo $this->script()->outputScript('/asset/js/??modules/lab/2.0.3/lab.js,modules/jquery/1.11.1/jquery.min.js')->lastWait(function() {
            //页面中所有JS加载完毕后才开始执行的
            return '__wait(false, true);';
        });
        ?>
        
        <script type="text/javascript">
            __wait(function(){
                $('.aj-nav').click(function(e) {
                    e.preventDefault();
                    if ($('i', this).hasClass('icon-folder-close')) {
                        $('i', this).removeClass('icon-folder-close').addClass('icon-folder-open');
                    } else {
                        $('i', this).removeClass('icon-folder-open').addClass('icon-folder-close');
                    }
                    $(this).next().slideToggle();
                });

                // Bootstrap Table Class
                $('table').addClass('table');
            });
        </script>
    </body>
</html>