<!doctype html> 
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $this->headTitle('开放空间 - 文档馆')?></title>
        <?php echo $this->headMeta('开放空间', 'keywords')->headMeta('开放空间', 'description')?>
        <?php $this->headLink()->prependStylesheet('/asset/css/page/md_shell.css')?>
        <?php echo $this->headLink()?>
        <?php echo $this->initPageNecessary()?>
    </head>
    <body>
        <div class="container-fluid fluid-height wrapper">
			<div class="navbar navbar-default navbar-fixed-top">
				<div class="navbar-inner">
					<a class="brand pull-left" href="<?php echo $this->homepageUrl;?>">开放空间 - 文档馆</a>
				</div>
			</div>

			<div class="row-fluid columns content">
				<div id="leftBoxId" class="left-column article-tree span3">
					<div id="sub-nav-collapse" class="collapse in">
						<!-- Navigation -->
						<?php echo $this->navTrees; ?>
					</div>
				</div>
				<div class="right-column content-area span9">
					<div class="content-page">
						<article>
                            <?php echo $scriptContent ?>
						</article>
					</div>
				</div>
			</div>
		</div>
       
        <div id="rightMenuBoxId" class="rmenu">
            <div class="rmenu-item rmenu-item-bb">
                <a href="javascript:history.back();"><i class="icon-folder-close"></i>创建父目录</a>
            </div>
            <div class="rmenu-item rmenu-item-bb">
                <a href="javascript:history.back();"><i class="icon-folder-close"></i>创建子目录</a>
            </div>
            <div class="rmenu-item">
                <a href="javascript:history.back();"><i class="icon-file"></i>创建文档</a>
            </div>
        </div>
        
        <?php
        echo $this->script()->outputScript('/asset/js/??modules/lab/2.0.3/lab.js,modules/jquery/1.11.1/jquery.min.js,modules/jquery/plugin/equalHeight/jquery.equalHeight.js')->lastWait(function() {
            //页面中所有JS加载完毕后才开始执行的
            return '__wait(false, true);';
        });
        ?>
        
        <script type="text/javascript">
            function showRightMenu(e)
            {
                var leftBoxDom = $('#leftBoxId').get(0);
                var menuBoxDom = $('#rightMenuBoxId').get(0);
                        
                /*获取当前鼠标右键按下后的位置，据此定义菜单显示的位置*/
                var rightedge  = leftBoxDom.clientWidth - e.clientX;
                var bottomedge = leftBoxDom.clientHeight- e.clientY;

                /*如果从鼠标位置到容器右边的空间小于菜单的宽度，就定位菜单的左坐标（Left）为当前鼠标位置向左一个菜单宽度*/
                if (rightedge < menuBoxDom.offsetWidth) {          
                    menuBoxDom.style.left = leftBoxDom.scrollLeft + e.clientX - menuBoxDom.offsetWidth + "px";
                } else {/*否则，就定位菜单的左坐标为当前鼠标位置*/
                    menuBoxDom.style.left = leftBoxDom.scrollLeft + e.clientX + "px";
                }
                
                /*如果从鼠标位置到容器下边的空间小于菜单的高度，就定位菜单的上坐标（Top）为当前鼠标位置向上一个菜单高度*/
                if (bottomedge < menuBoxDom.offsetHeight) {
                    menuBoxDom.style.top = leftBoxDom.scrollTop + e.clientY - menuBoxDom.offsetHeight + "px";
                } else {/*否则，就定位菜单的上坐标为当前鼠标位置*/
                    menuBoxDom.style.top = leftBoxDom.scrollTop + e.clientY + "px";
                }
                
                $('#rightMenuBoxId').show();
            }
            
            function hideRightMenu()
            {
                $('#rightMenuBoxId').hide();
            }
            
            __wait(function(){
                // Bootstrap Table Class
                $('table').addClass('table');
                
                //绑定目录折叠
                $('.aj-nav').click(function(e) {
                    e.preventDefault();
                    if ($('i', this).hasClass('icon-folder-close')) {
                        $('i', this).removeClass('icon-folder-close').addClass('icon-folder-open');
                    } else {
                        $('i', this).removeClass('icon-folder-open').addClass('icon-folder-close');
                    }
                    $(this).next().slideToggle();
                });
                
                //目录右键菜单
                $('.aj-nav').on('contextmenu', function(e){
                    e.cancelBubble = true;
                    e.stopPropagation();
                    showRightMenu(e);
                    return false;
                });
                $('#rightMenuBoxId').on('contextmenu', function(e){
                    e.cancelBubble = true;
                    e.stopPropagation();
                    return false;
                });
                $(document.body).on('click', function(){
                    hideRightMenu();
                });
            });
        </script>
    </body>
</html>